Repository jenkinsci/workflow-job-plugin, pull requests merged in 2021-06, with the labels that each got.

#195 Update plugin POM and BOM
  pom.xml
Labels: chore, dependencies, maintenance

#194 Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`
  src/test/java/org/jenkinsci/plugins/workflow/job/ReverseBuildTriggerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunWithFlowExecutionListenerTest.java
Labels: enhancement

#146 Do not print FlowDurabilityHint to build log
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: maintenance
