Repository jenkinsci/workflow-job-plugin, pull requests merged in 2021-11, with the labels that each got.

#220 No need to override `reuseForks`
  pom.xml
Labels: tests

#223 Update Dependabot configuration
  .github/dependabot.yml
Labels: chore, maintenance

#224 Use container agent in `Jenkinsfile`
  Jenkinsfile
Labels: maintenance
