Repository jenkinsci/workflow-job-plugin, pull requests merged in 2021-12, with the labels that each got.

#221 Use SVG icons where possible
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/main.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/sidepanel.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/index.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/sidepanel.jelly
Labels: enhancement

#225 Miscellaneous code cleanup
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
  src/main/java/org/jenkinsci/plugins/workflow/job/console/NewNodeConsoleNote.java
  src/main/java/org/jenkinsci/plugins/workflow/job/views/GraphVizAction.java
  src/test/java/org/jenkinsci/plugins/workflow/job/BuildTriggerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/CLITest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/CpsPersistenceTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/ReverseBuildTriggerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowJobTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunRestartTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/console/DefaultLogStorageTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/console/TaskListenerDecoratorTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobPropertyTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/properties/PipelineTriggersJobPropertyTest.java
Labels: chore

#227 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  README.md
  pom.xml
Labels: maintenance
