Repository jenkinsci/workflow-job-plugin, pull requests merged in 2022-07, with the labels that each got.

#274 Modernize icons
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/job/views/FlowGraphTableAction.java
  src/main/resources/images/symbols/build-steps.svg
  src/main/resources/images/symbols/edit-note.svg
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/main.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/sidepanel.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/index.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/sidepanel.jelly
Labels: enhancement

#278 [JENKINS-68981] Change access level of `WorkflowRun#isInProgress` to `public`
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: enhancement

#279 Remove java 8 from CI
  Jenkinsfile
Labels: developer

#261 Update project configuration screen
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
  src/main/resources/images/symbols/advanced-project-options.svg
  src/main/resources/images/symbols/pipeline.svg
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/configure-entries.jelly
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowJobTest.java
Labels: enhancement

#284 `Descriptor#bindJSON` not `StaplerRequest#bindJSON`
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
Labels: bug

#281 Remove hierarchal sidebar links
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/sidepanel.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/sidepanel.jelly
Labels: enhancement
