Repository jenkinsci/workflow-job-plugin, pull requests merged in 2022-01, with the labels that each got.

#230 EOL JSR 305
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
  src/main/java/org/jenkinsci/plugins/workflow/job/console/NewNodeConsoleNote.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableResumeJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/DurabilityHintJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/PipelineTriggersJobProperty.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunWithFlowExecutionListenerTest.java
Labels: dependencies

#217 Missing nullability annotations added
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableResumeJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/DurabilityHintJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/PipelineTriggersJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/views/FlowGraphAction.java
  src/main/java/org/jenkinsci/plugins/workflow/job/views/FlowGraphTableAction.java
  src/main/java/org/jenkinsci/plugins/workflow/job/views/GraphVizAction.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunRestartTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/console/TaskListenerDecoratorTest.java
Labels: chore

#235 JENKINS-67522 Use same animation as core for pipeline logs
  pom.xml
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/console.jelly
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunRestartTest.java
Labels: enhancement

#234 Switch to SVG icon
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
  src/main/webapp/images/48x48/pipelinejob.png
  src/main/webapp/images/pipelinejob.svg
Labels: enhancement

#226 Ensure all runs with corrupt execution are marked as failures
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: bug

#215 New Item>Pipeline ES translation - Hacktoberfest
  src/main/resources/org/jenkinsci/plugins/workflow/job/Messages_es.properties
Labels: hacktoberfest-accepted, documentation
