Repository jenkinsci/workflow-job-plugin, pull requests merged in 2023-08, with the labels that each got.

#375 Deleting old comment about closing listener
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: chore

#352 Implementing `Job.getEstimatedDurationCandidates`
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowJobTest.java
Labels: bug

#377 Expose `NewNodeConsoleNote` as `Beta.class` so `LogStorage` implementations can interact with it
  src/main/java/org/jenkinsci/plugins/workflow/job/console/NewNodeConsoleNote.java
Labels: developer

#380 Remove unnecessary exclusion
  pom.xml
Labels: skip-changelog
