Repository jenkinsci/workflow-job-plugin, pull requests merged in 2024-10, with the labels that each got.

#411 [JENKINS-69916] Un-inline `WorkflowJob/configure-entries.jelly`
  pom.xml
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/configure-entries.jelly
Labels: enhancement

#473 Upgrade plugin parent POM to latest
  pom.xml
Labels: skip-changelog

#474 Stop using deprecated method
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: internal

#476 Migrate to EE 9 types
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
  src/main/java/org/jenkinsci/plugins/workflow/job/properties/PipelineTriggersJobProperty.java
  src/main/java/org/jenkinsci/plugins/workflow/job/views/GraphVizAction.java
Labels: internal

#477 [JENKINS-73875] CSP compatibility for `NewNodeConsoleNote`
  src/main/resources/org/jenkinsci/plugins/workflow/job/console/NewNodeConsoleNote/script.js
Labels: enhancement

#470 [JENKINS-73824][JENKINS-73835] Remove redundant log rotation after changes in core and add regression tests related to deleting Pipeline jobs and builds
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowJobTest.java
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunTest.java
Labels: bug

#483 Drop core dependency from 2.481 to 2.479.1
  pom.xml
Labels: enhancement
