Repository jenkinsci/workflow-job-plugin, pull requests merged in 2024-07, with the labels that each got.

#445 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#430 Create LICENSE
  LICENSE
Labels: documentation

#439 Add download option to 'Console output', move 'View as plain text' and 'Copy' buttons to app bar
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/console.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowRun/sidepanel.jelly
Labels: enhancement
