Repository jenkinsci/workflow-job-plugin, pull requests merged in 2025-04, with the labels that each got.

#524 Remove call to a deprecated no-op method
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: chore

#523 Fix a deadlock between `WorkflowRun#save` and `WorkflowRun#reload`
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: bug

#528 `DefaultLogStorageTest.performance`
  src/test/java/org/jenkinsci/plugins/workflow/job/console/DefaultLogStorageTest.java
Labels: tests
