Repository jenkinsci/workflow-job-plugin, pull requests merged in 2025-01, with the labels that each got.

#497 Use secondary text color variable
  src/main/resources/org/jenkinsci/plugins/workflow/job/console/NewNodeConsoleNote/script.js
  src/main/resources/org/jenkinsci/plugins/workflow/job/console/NewNodeConsoleNote/style.css
Labels: enhancement

#479 Refine content and appearance of the project 'Configure' screen
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/configure-entries.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/WorkflowJob/configure-entries.properties
  src/main/resources/org/jenkinsci/plugins/workflow/job/properties/PipelineTriggersJobProperty/config.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/job/properties/PipelineTriggersJobProperty/config.properties
  src/main/resources/org/jenkinsci/plugins/workflow/job/properties/PipelineTriggersJobProperty/config_ja.properties
Labels: enhancement

#502 Flaky `WorkflowRunTest.logRotationOnlyProcessesCompletedBuilds` on Windows
  src/test/java/org/jenkinsci/plugins/workflow/job/WorkflowRunTest.java
Labels: tests

#499 Implementing `FlowExecutionOwner.getExternalizableId`
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: developer

#503 Remove synchronization from `WorkflowRun.doStop`
  src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java
Labels: bug
